# Generated by Django 2.1.1 on 2018-09-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.City')),
            ],
        ),
        migrations.AddField(
            model_name='dong',
            name='gu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Gu'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='dong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Dong'),
        ),
        migrations.AddField(
            model_name='address',
            name='gu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Gu'),
        ),
    ]
