# Generated by Django 2.1.1 on 2018-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남성'), ('f', '여성'), ('x', '선택안함')], default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_position',
            field=models.CharField(blank=True, choices=[('PG', '포인트 가드'), ('SG', '슈팅 가드'), ('SF', '스몰 포워드'), ('PF', '파워 포워드'), ('C', '센터')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_position',
            field=models.CharField(blank=True, choices=[('PG', '포인트 가드'), ('SG', '슈팅 가드'), ('SF', '스몰 포워드'), ('PF', '파워 포워드'), ('C', '센터')], max_length=25),
        ),
    ]
