# Generated by Django 2.1.1 on 2018-09-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='no_basket',
            field=models.IntegerField(),
        ),
    ]
