# Generated by Django 2.1.1 on 2018-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='court',
            name='bench',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='coordinate_x',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='court',
            name='coordinate_y',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='court',
            name='no_basket',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='parking',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='showerbox',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
