# Generated by Django 2.1.1 on 2018-09-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20180914_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['name']},
        ),
    ]
